Hacktoberfest blog post
uptane/uptane.github.io pull request #110
Opened 2023-10-27 20:21 UTC by hexsecs

# Summary of Changes

Created a blog article to discuss our work with Hacktoberfest. Improvements to the text welcome.

## Related Issue

## Checklist

- [x] I have read and followed the [project's contribution guidelines](https://github.com/secure-systems-lab/lab-guidelines/blob/master/dev-workflow.md), including code style and commit message conventions.
- [x] My code is well-documented, and I've updated relevant documentation.
- [x] I have added or updated test cases to ensure the code's functionality.
- [x] I have tested these changes on my local environment.
- [x] All tests pass, and there are no new linting errors.
- [x] I have reviewed and proofread my code and the changes.
- [x] The branch is up-to-date with the base branch.

## Screenshots (if applicable)

<img width="786" alt="image" src="https://github.com/uptane/uptane.github.io/assets/89217603/170c1ea7-e0df-4b17-8031-bd4af002c8c1">

## Additional Context

Add any additional context or information that might be helpful for reviewers.

## Reviewer(s)

@jhdalek55 @Abhijay007

2023-10-28 02:38 UTC, Abhijay007 approved these changes
LGTM, we plan to further categorize the blogs in the near future. Once we have a sufficient number of blogs, for example, we might require at least four blogs to create meaningful categories. I'll investigate the options and customizations available for blogs using Docusaurus.

2023-10-29 23:13 UTC, jhdalek55 requested changes
I'm requesting one tiny deletion. Otherwise, this looks great. I suggest we cross post this on the new LinkedIn page as well.

2023-10-29 23:13 UTC, jhdalek55 commented on blog/2023-10-28-hacktoberfest/index.md
> +This Hacktoberfest, developers from around the globe 🌍 can contribute to Uptane's repository, helping to enhance the security framework and make our vehicles more secure. Whether you're a seasoned de
One small fix here. Take out the word "our" in the first sentence. Uptane doesn't create or own the vehicles.
```suggestion
This Hacktoberfest, developers from around the globe 🌍 can contribute to Uptane's repository, helping to enhance the security framework and make vehicles more secure. Whether you're a seasoned developer or a newbie looking to make your first open-source contribution, Uptane welcomes you with open arms 🤗.
```

2023-10-30 00:10 UTC, merged

2023-10-30 00:11 UTC, hexsecs commented
> I'm requesting one tiny deletion. Otherwise, this looks great. I suggest we cross post this on the new LinkedIn page as well.

@jhdalek55 - I incorporated your change request and merged the pull request.