Shubhusion/issue98
uptane/uptane.github.io pull request #142
Opened 2023-11-14 10:08 UTC by shubhusion

# Summary of Changes

- Redesigned the Readme.md 
- Added Badges 
- Added Troubleshooting Tips Section Under Running
- Added Connect with Us Section 

## Related Issue

Closes #98 

## Checklist

- [x] I have read and followed the [project's contribution guidelines](https://github.com/secure-systems-lab/lab-guidelines/blob/master/dev-workflow.md), including code style and commit message conventions.
- [x] My code is well-documented, and I've updated relevant documentation.
- [x] I have added or updated test cases to ensure the code's functionality.
- [x] I have tested these changes on my local environment.
- [x] All tests pass, and there are no new linting errors.
- [x] I have reviewed and proofread my code and the changes.
- [x] The branch is up-to-date with the base branch.

## Screenshots (if applicable)

Before Changes:
![image](https://github.com/uptane/uptane.github.io/assets/96301987/a4ca2ef6-7a00-4fa0-a644-c4db8bea9dbb)

After Changes:
![image](https://github.com/uptane/uptane.github.io/assets/96301987/a51c97a6-0b21-4ef2-89d5-11a752d3976d)

## Additional Context

Add any additional context or information that might be helpful for reviewers.

## Reviewer(s)

@hexsecs @jhdalek55

2023-11-16 12:41 UTC, jhdalek55 requested changes
Except for spelling out the word "information," this is fine with me.

2023-11-16 12:41 UTC, jhdalek55 commented on README.md
> +For more info please refer to Uptane [Contribution guidelines](https://github.com/uptane/uptane-standard/blob/master/CONTRIBUTING.md)
```suggestion
For more information, please refer to Uptane [Contribution guidelines](https://github.com/uptane/uptane-standard/blob/master/CONTRIBUTING.md)
```

2023-11-16 18:17 UTC, hexsecs commented on README.md
> +[![Discord](https://img.shields.io/discord/uWyT6gDCqx?label=Discord&logo=discord)](https://discord.gg/uWyT6gDCqx)
This link doesn't work. You need the server ID.
https://img.shields.io/discord/1157306344097988640?label=Discord&logo=discord

2023-11-16 18:22 UTC, hexsecs commented on README.md
> +[![Discord](https://img.shields.io/discord/uWyT6gDCqx?label=Discord&logo=discord)](https://discord.gg/uWyT6gDCqx)
```suggestion
[![Discord](https://img.shields.io/discord/1157306344097988640?label=Discord&logo=discord)](https://discord.gg/uWyT6gDCqx)
```

2023-11-16 18:59 UTC, hexsecs commented on README.md
> +<img  src="https://github.com/uptane/uptane.github.io/blob/main/static/img/uptane-logo.svg"  width="500" />
```suggestion
<img  src="https://github.com/uptane/uptane.github.io/blob/main/static/img/uptane_logo_light.svg"  width="500" />
```
Should use the new logo

2023-11-17 07:58 UTC, Abhijay007 requested changes
@shubhusion Could you please change the text 'built with' to a badge instead

![image](https://github.com/uptane/uptane.github.io/assets/64387054/343e2cff-6766-40d5-819d-354537a656e6)

something like this : 
![image](https://github.com/uptane/uptane.github.io/assets/64387054/fe4a9ee9-ad8f-42fe-8676-3b1b7820043d)


you can use : https://forthebadge.com/#/generator for this purpose

2023-11-17 13:08 UTC, Abhijay007 commented
> @shubhusion Could you please change the text 'built with' to a badge instead
> 
> ![image](https://user-images.githubusercontent.com/64387054/283721680-343e2cff-6766-40d5-819d-354537a656e6.png)
> 
> something like this : ![image](https://user-images.githubusercontent.com/64387054/283722059-fe4a9ee9-ad8f-42fe-8676-3b1b7820043d.png)
> 
> you can use : https://forthebadge.com/#/generator for this purpose

Hi @shubhusion instead of forthebadge can you please use https://shields.io/badges

2023-11-17 13:50 UTC, shubhusion commented
> > @shubhusion Could you please change the text 'built with' to a badge instead
> > ![image](https://user-images.githubusercontent.com/64387054/283721680-343e2cff-6766-40d5-819d-354537a656e6.png)
> > something like this : ![image](https://user-images.githubusercontent.com/64387054/283722059-fe4a9ee9-ad8f-42fe-8676-3b1b7820043d.png)
> > you can use : https://forthebadge.com/#/generator for this purpose
> 
> Hi @shubhusion instead of forthebadge can you please use https://shields.io/badges

![image](https://github.com/uptane/uptane.github.io/assets/96301987/37a1b354-783e-4525-9213-0c3256650da3)
@Abhijay007 let me know if this works?

2023-11-17 13:56 UTC, Abhijay007 commented
> > > @shubhusion Could you please change the text 'built with' to a badge instead
> > > ![image](https://user-images.githubusercontent.com/64387054/283721680-343e2cff-6766-40d5-819d-354537a656e6.png)
> > > something like this : ![image](https://user-images.githubusercontent.com/64387054/283722059-fe4a9ee9-ad8f-42fe-8676-3b1b7820043d.png)
> > > you can use : https://forthebadge.com/#/generator for this purpose
> > 
> > 
> > Hi @shubhusion instead of forthebadge can you please use https://shields.io/badges
> 
> ![image](https://user-images.githubusercontent.com/96301987/283822070-37a1b354-783e-4525-9213-0c3256650da3.png) @Abhijay007 let me know if this works?

ya it LGTM

2023-11-17 14:25 UTC, hexsecs commented
That's perfect. If you can update to that, I can merge the PR today.

2023-11-17 14:31 UTC, hexsecs commented on README.md
> +  Built With <img src="https://img.shields.io/badge/docusaurus-231F20.svg?style=flat-square&logo=docusaurus&logoColor=Green" alt="docusaurus" width="120"/>
Update to harmonized badge (see comment from @Abhijay007 )
https://github.com/uptane/uptane.github.io/pull/142#issuecomment-1816476877

2023-11-17 14:31 UTC, hexsecs requested changes
See comment. Should be GTG after that.

2023-11-17 14:57 UTC, Abhijay007 approved these changes
LGTM 👍

2023-11-17 17:22 UTC, hexsecs approved these changes

2023-11-17 17:24 UTC, merged