(Docs): Added 24pullRequests announcement post
uptane/uptane.github.io pull request #158
Opened 2023-12-01 17:59 UTC by Abhijay007

# Summary of Changes

Added 24pullRequests announcement post

## Checklist

- [x] I have read and followed the [project's contribution guidelines](https://github.com/secure-systems-lab/lab-guidelines/blob/master/dev-workflow.md), including code style and commit message conventions.
- [x] My code is well-documented, and I've updated relevant documentation.
- [x] I have tested these changes on my local environment.
- [x] All tests pass, and there are no new linting errors.
- [x] I have reviewed and proofread my code and the changes.
- [x] The branch is up-to-date with the base branch.

2023-12-01 23:20 UTC, jhdalek55 requested changes
A few small syntactic changes...

2023-12-01 23:20 UTC, jhdalek55 commented on blog/2023-12-01-24pullRequests/index.md
> +As the winter season approaches, [Uptane](https://uptane.org/) is thrilled to announce its participation in the annual 24 Pull Requests event! This initiative is a testament to our commitment to coll
```suggestion
As winter approaches, [Uptane](https://uptane.org/) is thrilled to announce its participation in the annual 24 Pull Requests event! This initiative is a testament to our  project's continuing commitment to collaboration and community building.

```

2023-12-01 23:20 UTC, jhdalek55 commented on blog/2023-12-01-24pullRequests/index.md
> +Uptane stands as a robust framework designed to fortify the security of software updates within the automotive industry. Uptane addresses the need for a reliable solution, ensuring the safety and int
```suggestion
Uptane is a robust framework designed to fortify the security of software updates within the automotive industry. It  addresses the growing need for a reliable solution that can ensure the safety and integrity of software updates for vehicles.
```

2023-12-01 23:20 UTC, jhdalek55 commented on blog/2023-12-01-24pullRequests/index.md
> +The [24 Pull Requests](https://24pullrequests.com/) event is an annual community-organized celebration, inviting developers to contribute to open source projects during the holiday season. Join us in
```suggestion
The [24 Pull Requests](https://24pullrequests.com/) event is an annual community-organized celebration in which developers are invited to contribute to open source projects over the holiday season. Join us in spreading the joy of collaboration by submitting 24 pull requests between December 1 and December 24.
```

2023-12-05 14:51 UTC, hexsecs requested changes
Just the logo comment everything else LGTM.

2023-12-05 14:51 UTC, hexsecs commented on blog/2023-12-01-24pullRequests/bannerImage.png
Can you use the updated Uptane logo? I would like to deprecate the using the old one for new media content.

2023-12-11 16:52 UTC, merged