Rename to "Deployment Best Practices".
uptane/uptane.github.io pull request #30
Opened 2020-10-27 15:14 UTC by patrickvacek

I have not changed any URLs.

Arguably depends on uptane/deployment-considerations#58.

2020-12-11 16:51 UTC, jhdalek55 commented
@pattivacek  Is this a loose thread we need to fix before we send out V.1.1.0? It's a separate issue from the actual document, but we do want to strive for consistency.

2020-12-14 08:44 UTC, pattivacek commented
I think this is pretty uncontroversial; it's just following the naming consensus with a couple very minor other changes. I think it can safely be merged now unless you or others disagree.

2020-12-14 12:48 UTC, jhdalek55 requested changes
I don't know if these have already been fixed in a previous pass. And there was one typos. If this is fixed I will merge.

2020-12-14 12:48 UTC, jhdalek55 commented on participate.md
> +Uptane design and implementation is defined in the [Uptane Standards document](https://uptane.github.io/uptane-standard/uptane-standard.html) and supplmented by the [Deployment Best Practices](https:
supplemented is misspelled

2020-12-14 12:48 UTC, jhdalek55 commented on reference_pouf.md
> +All XML-RPC traffic supported in this POUF is transmitted over TCP/IP and does not support CAN or other network types. For more information about internal vehicle communication, see the [Deployment B
change last line to  "...see the Deployment Best Practices document"

2020-12-14 12:48 UTC, jhdalek55 commented on reference_pouf.md
> +To access a reliable current time as needed for the [In Vehicle Implementation Requirements](https://uptane.github.io/uptane-standard/uptane-standard.html#in-vehicle-implementation-requirements), ECU
"the Deployment Best Practices document.

2020-12-14 12:56 UTC, pattivacek commented
Fixed all issues.

2020-12-14 13:04 UTC, merged

2020-12-14 13:04 UTC, jhdalek55 commented
Done. Thanks.