Update links to repos hosted in the uptane namespace.
uptane/uptane.github.io pull request #53
Opened 2022-07-26 08:28 UTC by pattivacek

Also remove reference to the obsolete reference implementation. There were some bits about maintainership that _maybe_ could still apply to the code that is on GitHub, but I didn't want to assume that. I don't think we've had a lot of issues around that lately, so I think for now it's best just to remove that and reconsider at a later time if additional text is necessary.

In the process, I noticed that the [People](https://uptane.github.io/people.html) and [Governance](https://uptane.github.io/governance.html) pages have a lot of redundant material. Can we consider merging those pages, or otherwise removing the duplicate parts?

2022-07-28 06:14 UTC, pattivacek commented
FYI @tkfu @jhdalek55 @JustinCappos

2022-08-15 07:17 UTC, pattivacek commented
Hey, it's been almost three weeks. Can I get a review?

2022-08-15 10:38 UTC, jhdalek55 commented
I'll take a look later today. I also put it on the agenda for tomorrow's meeting.

2022-08-15 15:27 UTC, jhdalek55 requested changes
I've marked two changes that should be made.

2022-08-15 15:27 UTC, jhdalek55 commented on adoptions.md
> +First, Uptane is incorporated in [Automotive Grade Linux](https://www.automotivelinux.org/), which is supported by [major OEMs and suppliers](https://www.automotivelinux.org/about/members/). This is
```suggestion
First, Uptane is incorporated in [Automotive Grade Linux](https://www.automotivelinux.org/), which is supported by [major OEMs and suppliers](https://www.automotivelinux.org/about/members/). Uptane's presence in AGL is via [aktualizr](https://github.com/uptane/aktualizr), which is also integrated into the [OTA Community Edition](https://github.com/uptane/ota-community-edition/) and [GENIVI](https://www.genivi.org/).
```

2022-08-15 15:27 UTC, jhdalek55 commented on participate.md
>  [Justin Cappos](mailto:jcappos@nyu.edu) or maintainer [Sebastien Awwad](mailto: sebastien.awwad@nyu.edu).
I believe the maintainer contact should be switched to me
```suggestion
[Justin Cappos](mailto:jcappos@nyu.edu) or maintainer [Lois Anne DeLong](mailto: lad278@nyu.edu).
```

2022-08-16 15:41 UTC, pattivacek commented
> My apologies for not responding sooner @pattivacek. I'm afraid my Uptane focus has been elsewhere lately. I made one suggestion and one correction in my review.

No worries, thanks for checking! I've incorporated your changes.

> Your comment on the overlap between Governance and People is a valid one We are starting to compile issues for a planned revision of the website. Could you write this up as an issue for this purpose.?

Done, see https://github.com/uptane/uptane.github.io/issues/55.

2022-09-02 16:17 UTC, jhdalek55 commented
Can we get a review other than mine here?

2022-09-02 16:20 UTC, jhdalek55 approved these changes

2022-09-27 14:57 UTC, hexsecs approved these changes
I think this looks good to me.

2022-09-27 15:09 UTC, pattivacek commented
Thanks! Now it just needs to be merged, which I don't have rights to. Can someone do that for me, please?

2022-09-27 15:57 UTC, merged

2022-09-27 16:01 UTC, jhdalek55 commented
Done