(Docs) : Added contributing guidelines
uptane/uptane.github.io pull request #61
Opened 2023-04-09 11:12 UTC by Abhijay007

Added Contributing guidelines

2023-04-13 16:53 UTC, Abhijay007 commented
@jhdalek55 review required :)

2023-05-08 21:43 UTC, jhdalek55 commented
I haven't reviewed this yet, but I'm wondering if we might want to think about the purpose of adding this here. We definitely want people to contribute ideas to the website, but I'm a little unsure about whether we want direct contributions to the text.  This is the face of the project and maybe we want to exercise some control here?  I may be completely wrong about this, so I'll just look at the text for now.

2023-05-08 22:01 UTC, jhdalek55 requested changes
The organization of headers and subheads was not logical. Also, there were a few sentence structure issues.

2023-05-08 22:01 UTC, jhdalek55 commented on README.md
> +After you have a successful testing in local with your changes, you are ready to commit those changes.
```suggestion
After you have successfully tested your changes locally, you are ready to commit those changes.
```

2023-05-09 06:01 UTC, Abhijay007 commented
> I haven't reviewed this yet, but I'm wondering if we might want to think about the purpose of adding this here. We definitely want people to contribute ideas to the website, but I'm a little unsure about whether we want direct contributions to the text. This is the face of the project and maybe we want to exercise some control here? I may be completely wrong about this, so I'll just look at the text for now.


@jhdalek55  Thank you for sharing your thoughts on this, I agree with you, I think we might need to create a separate `contributing.md` file for this purpose. Alternatively, we can also add these guidelines to the wiki and provide a link to those documents (`as a link to contributing guidelines`).

However, I would like to point out that these guidelines might change soon as we are still unsure about how we will proceed to improve the site. If we decide to stick with Jekyll, then these guidelines would make sense, but if we need to iterate, we may need to revise them.

For now, I think it would be best to put this on hold, although I will make the changes you suggested.

2023-10-13 15:00 UTC, Abhijay007 commented
new guidelines are needed as site is updated

2023-10-13 15:00 UTC, closed without merging

2023-10-13 15:18 UTC, jhdalek55 commented
Sorry. I don't know how to submit a PR now that the MD files are gone.

2023-10-13 15:19 UTC, jhdalek55 commented
I don't know how to submit the revised text as the MD files are now gone.

On Fri, Oct 13, 2023 at 11:12 AM Abhijay Jain ***@***.***>
wrote:

> sure, submit a pull request for this and if some changes are needed, we
> will create a new issue for that
>
> On Fri, Oct 13, 2023 at 8:40 PM Lois Anne DeLong ***@***.***>
> wrote:
>
> > Text has been drafted for this. Should I submit as a pull request?
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/uptane/uptane.github.io/pull/61#issuecomment-1761679560>
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uptane_uptane.github.io_pull_61-23issuecomment-2D1761679560-253E&d=DwQFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=cs3aE8F5m3rQG6AKbWKG5vocQe5qvPTXxyFiaIAofUioQTubYW93FiVbNOgXgPDC&s=gcBeYZdzi3Wq76CiRse1eAO_MNPv93Kl6wovxakMAvg&e=>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/APLHP3UMVLBZOZJPLJVTZ63X7FKW7ANCNFSM6AAAAAAWYBPS2Q>
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APLHP3UMVLBZOZJPLJVTZ63X7FKW7ANCNFSM6AAAAAAWYBPS2Q-253E&d=DwQFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=cs3aE8F5m3rQG6AKbWKG5vocQe5qvPTXxyFiaIAofUioQTubYW93FiVbNOgXgPDC&s=ZAXlsFryYSVh8tZ6xoAgMm7mnwbdWL7TS-VT6sdQ06w&e=>
> > .
> > You are receiving this because you modified the open/close state.Message
> > ID: ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uptane_uptane.github.io_pull_61-23issuecomment-2D1761682210&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=cs3aE8F5m3rQG6AKbWKG5vocQe5qvPTXxyFiaIAofUioQTubYW93FiVbNOgXgPDC&s=qCYq6PNCS6-B4PAyIUSWnoaSpzZsCMiJ79iz3XhSKgg&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADPGUX6OVD6HQMPXFY2DMDLX7FK6DANCNFSM6AAAAAAWYBPS2Q&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=cs3aE8F5m3rQG6AKbWKG5vocQe5qvPTXxyFiaIAofUioQTubYW93FiVbNOgXgPDC&s=4OW4Rt7XQubaiDz-l3qJ-pCtrGOYHjcfnwJyLrkSufk&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-13 15:38 UTC, Abhijay007 commented
> Sorry. I don't know how to submit a PR now that the MD files are gone.

you can create a new file contributing.md and can submit the PR with the revised text

2023-10-13 15:52 UTC, jhdalek55 commented
Done

On Fri, Oct 13, 2023 at 11:40 AM Lois A DeLong ***@***.***> wrote:

> Ok, I will try.
>
> Lois
>
> On Fri, Oct 13, 2023 at 11:39 AM Abhijay Jain ***@***.***>
> wrote:
>
>> Sorry. I don't know how to submit a PR now that the MD files are gone.
>>
>> you can create a new file named contributing.md and can submit the PR
>> with the revised text
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uptane_uptane.github.io_pull_61-23issuecomment-2D1761721495&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=77Z2InA5Xe1B-pjoYrzlYiBwzEx-IG93iZRDrAp_g2JfH1r0sdHjTh1mLSOkUXUZ&s=HzjFPk7tHBW44YC0eBxzjw5J_1jQBnQ0ImGqsx5LwPE&e=>,
>> or unsubscribe
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADPGUX22MM75O4U7HAQFO7TX7FOBJANCNFSM6AAAAAAWYBPS2Q&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=77Z2InA5Xe1B-pjoYrzlYiBwzEx-IG93iZRDrAp_g2JfH1r0sdHjTh1mLSOkUXUZ&s=4BjmBPw3KWHDlGdZnPUrNXjn1JXgnJ4039eBoYg9Uc8&e=>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>